# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3274bfc7f81cd9b0a8676515476bf3ed59de0de35dac2934593ce95d330a2b1a7092a756d01660833d74afe469bb054e02ab765f382208443319c064cadf559

test:
  secret_key_base: 11930d5152900b666f107d1275e3633f72ad484d83c291bee729b8b3f7c5f6d84867efb66f6c2f0cfa41ec3610528836d21685a3655a7c24b793048855b19a85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
